packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
catalog:
  "@cloudflare/workers-types": ^4.20251213.0
  "@libsql/client": 0.15.15
  "@types/node": ^22.13.14
  alchemy: ^0.90.0
  dotenv: ^17.2.2
  libsql: 0.5.22
  typescript: ^5
  zod: ^4.1.13
