packages:
  - apps/*
  - packages/*
allowBuilds:
  better-sqlite3: true
  esbuild: true
  msw: true
  sharp: true
  workerd: true
catalog:
  "@cloudflare/workers-types": ^4.20260413.1
  "@libsql/client": 0.15.15
  "@types/node": ^22.19.17
  alchemy: ^0.90.0
  dotenv: ^17.4.2
  libsql: 0.5.22
  typescript: ^5.9.3
  zod: ^4.3.6
